var order = {
  id: "00000221",
  altOrderId: "BKGYbUaoWZ2WgIN__yOvPI9Xb-nZGg1WB1SMMwE5RaE",
  ccType: "Visa",
  shipCountry: "USA",
  shipped: "20210524_1445",
  orderStatus: "NEW",
  total: 1118.47,
  shipping: 119.99,
  tax: 92.89,
  cartTotalQuantity: 3,
  totalDiscount: 0,
  couponCode: "",
  orderDateTime: "2021-05-21 10:45:29-0400",
  categories: [],
  subCategories: [],
  products: [
    {
      id: "APK-12000-L2",
      name: "Bladen 2-Piece Sectional",
      brand: "Ashley",
      manufacturerSKU: null,
      upc: null,
      category: "Furniture/Living Room Furniture/Sectional Sofas",
      isCompositeProduct: true,
      dimension27: true,
      dimension35: "Brown/Beige",
      dimension37: "Contemporary Living",
      dimension38: "Fabric",
      dimension39: "Solid",
      dimension47: "Faux Leather",
      dimension68: 214.58,
      dimension15: "Home Delivery",
      metric1: 26,
      metric2: 999.99,
      price: 799.99,
      metric3: 200,
      variant: "Coffee",
      dimension43: "Variation Product",
      dimension110: true,
      dimension112: "FURNPRO",
      dimension113: true,
      dimension102: "HD",
      dimension134: false,
      dimension142: "7d1186f4617ed2dab6cfd92d00",
      dimension143: "MIXED",
      quantity: 1,
      couponCodesApplied: [],
      tax: { currencyCode: "USD", amount: "60.00" },
      totalDiscount: { currencyCode: "USD", amount: "0.00" },
      adjustedNetPrice: 799.99,
      standardPrice: 999.99,
      shipBy: "Kingswere Furniture LLC an Ashley Furniture HomeStore," + " Kingswere Furniture LLC an Ashley Furniture HomeStore",
      itmStatus: "Current",
      selectedPPSkus: "FURNPRO",
      dimension14: "In Stock",
      dimension16: "Place your order today, and we’ll ship as soon as" + " possible. Estimated delivery time is 8-14 weeks.",
      dimension126: 43,
      position: 1,
    },
    {
      id: "FURNPRO",
      name: "Furniture Protection Plan",
      brand: "Ashley",
      manufacturerSKU: null,
      upc: "",
      category: "",
      isCompositeProduct: false,
      dimension15: "Direct Ship",
      metric1: 29,
      metric2: 0.01,
      price: 99.99,
      metric3: 0,
      dimension43: "Product",
      dimension110: false,
      dimension102: "DS",
      dimension134: false,
      dimension142: "7d1186f4617ed2dab6cfd92d00",
      dimension143: "MIXED",
      quantity: 1,
      adjustedNetPrice: 99.99,
      standardPrice: 0.01,
      shipBy: "Ashcomm LLC ashleyfurniturehomestore.com",
      itmStatus: "Current",
      couponCodesApplied: [],
      tax: { currencyCode: "USD", amount: 7.5 },
      totalDiscount: { currencyCode: "USD", amount: "0.00" },
      dimension14: "In Stock",
      dimension16: "undefined",
      dimension126: null,
      position: 2,
    },
    {
      id: "A8000190",
      name: "O'keria Wall Art",
      brand: "Ashley",
      manufacturerSKU: null,
      upc: "024052354973",
      category: "Decor + Pillows/Wall Decor",
      isCompositeProduct: false,
      dimension35: "Brown/Beige,Green,White",
      dimension37: "Contemporary Living",
      dimension38: "Fabric",
      dimension68: 12,
      dimension15: "Direct Ship",
      metric1: 47,
      metric2: 229.99,
      price: 218.49,
      metric3: 11.5,
      dimension43: "Product",
      dimension110: false,
      dimension102: "DS",
      dimension134: false,
      dimension142: "7d1186f4617ed2dab6cfd92d00",
      dimension143: "MIXED",
      quantity: 1,
      adjustedNetPrice: 218.49,
      standardPrice: 229.99,
      shipBy: "Ashcomm LLC ashleyfurniturehomestore.com",
      itmStatus: "Current",
      couponCodesApplied: [],
      tax: { currencyCode: "USD", amount: 16.39 },
      totalDiscount: { currencyCode: "USD", amount: "0.00" },
      dimension14: "In Stock",
      dimension16: "Usually ships in 1 week",
      dimension126: 1,
      position: 3,
    },
  ],
};

var categories = [];
var subCategories = [];

var products = order.products;
products.map(function (item) {
  if (item.id) {
    var prodCategory = item.category.split("/")[0];
    categories.push(prodCategory != undefined ? prodCategory : "");
    var prodSubCategory = item.category.split("/")[1];
    subCategories.push(prodSubCategory != undefined ? prodSubCategory : "");
    quantity += item.quantity;
  }
});
console.log(cartTotal);
console.log(productIds);
console.log(categories);
console.log(subCategories);
console.log(quantity);
